In [1]:
import pandas as pd
brics = pd.read_csv("H:\Python\owid-covid-data.csv", index_col = 0)
brics

,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
iso_code,,,,,,,,,,,,,,,,,,,,,
AFG,Asia,Afghanistan,24/02/2020,5.0,5.0,NaN,NaN,NaN,NaN,0.126,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
AFG,Asia,Afghanistan,25/02/2020,5.0,0.0,NaN,NaN,NaN,NaN,0.126,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
AFG,Asia,Afghanistan,26/02/2020,5.0,0.0,NaN,NaN,NaN,NaN,0.126,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
AFG,Asia,Afghanistan,27/02/2020,5.0,0.0,NaN,NaN,NaN,NaN,0.126,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
AFG,Asia,Afghanistan,28/02/2020,5.0,0.0,NaN,NaN,NaN,NaN,0.126,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZWE,Africa,Zimbabwe,06/02/2022,230402.0,0.0,134.571,5362.0,0.0,3.571,15266.326,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
ZWE,Africa,Zimbabwe,07/02/2022,230402.0,0.0,105.143,5362.0,0.0,3.429,15266.326,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
ZWE,Africa,Zimbabwe,08/02/2022,230603.0,201.0,107.429,5366.0,4.0,2.286,15279.644,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
ZWE,Africa,Zimbabwe,09/02/2022,230740.0,137.0,104.000,5367.0,1.0,2.143,15288.722,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
ZWE,Africa,Zimbabwe,10/02/2022,231040.0,300.0,124.286,5373.0,6.0,2.286,15308.599,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN

In [14]:
import numpy as np
print(brics.head())
print(brics.shape)

         continent     location        date  total_cases  new_cases  \
iso_code
AFG           Asia  Afghanistan  24/02/2020          5.0        5.0
AFG           Asia  Afghanistan  25/02/2020          5.0        0.0
AFG           Asia  Afghanistan  26/02/2020          5.0        0.0
AFG           Asia  Afghanistan  27/02/2020          5.0        0.0
AFG           Asia  Afghanistan  28/02/2020          5.0        0.0

          new_cases_smoothed  total_deaths  new_deaths  new_deaths_smoothed  \
iso_code
AFG                      NaN           NaN         NaN                  NaN
AFG                      NaN           NaN         NaN                  NaN
AFG                      NaN           NaN         NaN                  NaN
AFG                      NaN           NaN         NaN                  NaN
AFG                      NaN           NaN         NaN                  NaN

          total_cases_per_million  ...  female_smokers  male_smokers  \
iso_code                           ...
AFG                         0.126  ...             NaN           NaN
AFG                         0.126  ...             NaN           NaN
AFG                         0.126  ...             NaN           NaN
AFG                         0.126  ...             NaN           NaN
AFG                         0.126  ...             NaN           NaN

          handwashing_facilities  hospital_beds_per_thousand  life_expectancy  \
iso_code
AFG                       37.746                         0.5            64.83
AFG                       37.746                         0.5            64.83
AFG                       37.746                         0.5            64.83
AFG                       37.746                         0.5            64.83
AFG                       37.746                         0.5            64.83

          human_development_index  excess_mortality_cumulative_absolute  \
iso_code
AFG                         0.511                                   NaN
AFG                         0.511                                   NaN
AFG                         0.511                                   NaN
AFG                         0.511                                   NaN
AFG                         0.511                                   NaN

          excess_mortality_cumulative  excess_mortality  \
iso_code
AFG                               NaN               NaN
AFG                               NaN               NaN
AFG                               NaN               NaN
AFG                               NaN               NaN
AFG                               NaN               NaN

          excess_mortality_cumulative_per_million
iso_code
AFG                                           NaN
AFG                                           NaN
AFG                                           NaN
AFG                                           NaN
AFG                                           NaN

[5 rows x 66 columns]
(160934, 66)

In [3]:
brics.info()

<class 'pandas.core.frame.DataFrame'>
Index: 160934 entries, AFG to ZWE
Data columns (total 66 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   continent                                   151277 non-null  object
 1   location                                    160934 non-null  object
 2   date                                        160934 non-null  object
 3   total_cases                                 158046 non-null  float64
 4   new_cases                                   158016 non-null  float64
 5   new_cases_smoothed                          156865 non-null  float64
 6   total_deaths                                140413 non-null  float64
 7   new_deaths                                  140587 non-null  float64
 8   new_deaths_smoothed                         140457 non-null  float64
 9   total_cases_per_million                     157311 non-null  float64
 10  new_cases_per_million                       157281 non-null  float64
 11  new_cases_smoothed_per_million              156135 non-null  float64
 12  total_deaths_per_million                    139691 non-null  float64
 13  new_deaths_per_million                      139865 non-null  float64
 14  new_deaths_smoothed_per_million             139735 non-null  float64
 15  reproduction_rate                           121653 non-null  float64
 16  icu_patients                                22669 non-null   float64
 17  icu_patients_per_million                    22669 non-null   float64
 18  hosp_patients                               23440 non-null   float64
 19  hosp_patients_per_million                   23440 non-null   float64
 20  weekly_icu_admissions                       5164 non-null    float64
 21  weekly_icu_admissions_per_million           5164 non-null    float64
 22  weekly_hosp_admissions                      10476 non-null   float64
 23  weekly_hosp_admissions_per_million          10476 non-null   float64
 24  new_tests                                   66141 non-null   float64
 25  total_tests                                 67328 non-null   float64
 26  total_tests_per_thousand                    67328 non-null   float64
 27  new_tests_per_thousand                      66141 non-null   float64
 28  new_tests_smoothed                          81560 non-null   float64
 29  new_tests_smoothed_per_thousand             81560 non-null   float64
 30  positive_rate                               76322 non-null   float64
 31  tests_per_case                              75762 non-null   float64
 32  tests_units                                 83793 non-null   object
 33  total_vaccinations                          42775 non-null   float64
 34  people_vaccinated                           40731 non-null   float64
 35  people_fully_vaccinated                     38038 non-null   float64
 36  total_boosters                              15154 non-null   float64
 37  new_vaccinations                            35423 non-null   float64
 38  new_vaccinations_smoothed                   79276 non-null   float64
 39  total_vaccinations_per_hundred              42775 non-null   float64
 40  people_vaccinated_per_hundred               40731 non-null   float64
 41  people_fully_vaccinated_per_hundred         38038 non-null   float64
 42  total_boosters_per_hundred                  15154 non-null   float64
 43  new_vaccinations_smoothed_per_million       79276 non-null   float64
 44  new_people_vaccinated_smoothed              78083 non-null   float64
 45  new_people_vaccinated_smoothed_per_hundred  78083 non-null   float64
 46  stringency_index                            126087 non-null  float64
 47  population                                  159882 non-null  float64
 48  population_density                          143243 non-null  float64
 49  median_age                                  133496 non-null  float64
 50  aged_65_older                               132048 non-null  float64
 51  aged_70_older                               132780 non-null  float64
 52  gdp_per_capita                              134118 non-null  float64
 53  extreme_poverty                             88375 non-null   float64
 54  cardiovasc_death_rate                       132466 non-null  float64
 55  diabetes_prevalence                         139407 non-null  float64
 56  female_smokers                              102727 non-null  float64
 57  male_smokers                                101253 non-null  float64
 58  handwashing_facilities                      66357 non-null   float64
 59  hospital_beds_per_thousand                  119789 non-null  float64
 60  life_expectancy                             150216 non-null  float64
 61  human_development_index                     131941 non-null  float64
 62  excess_mortality_cumulative_absolute        5529 non-null    float64
 63  excess_mortality_cumulative                 5529 non-null    float64
 64  excess_mortality                            5541 non-null    float64
 65  excess_mortality_cumulative_per_million     5529 non-null    float64
dtypes: float64(62), object(4)
memory usage: 82.3+ MB

In [6]:
brics[['date','population']]

                date  population
iso_code
AFG       24/02/2020  39835428.0
AFG       25/02/2020  39835428.0
AFG       26/02/2020  39835428.0
AFG       27/02/2020  39835428.0
AFG       28/02/2020  39835428.0
...              ...         ...
ZWE       06/02/2022  15092171.0
ZWE       07/02/2022  15092171.0
ZWE       08/02/2022  15092171.0
ZWE       09/02/2022  15092171.0
ZWE       10/02/2022  15092171.0

[160934 rows x 2 columns]

In [7]:
brics[1:4]

,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
iso_code,,,,,,,,,,,,,,,,,,,,,
AFG,Asia,Afghanistan,25/02/2020,5.0,0.0,NaN,NaN,NaN,NaN,0.126,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
AFG,Asia,Afghanistan,26/02/2020,5.0,0.0,NaN,NaN,NaN,NaN,0.126,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
AFG,Asia,Afghanistan,27/02/2020,5.0,0.0,NaN,NaN,NaN,NaN,0.126,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN

In [17]:
missing_values_count = brics.isnull().sum()
print(missing_values_count)

continent                                    9657
location                                        0
date                                            0
total_cases                                  2888
new_cases                                    2918
                                            ...
human_development_index                     28993
excess_mortality_cumulative_absolute       155405
excess_mortality_cumulative                155405
excess_mortality                           155393
excess_mortality_cumulative_per_million    155405
Length: 66, dtype: int64

In [18]:
droprows= brics.dropna()
print(brics.shape,droprows.shape)

(160934, 66) (0, 66)